#!/bin/bash

# ===========================================
# START SERVICES MANUALLY
# ===========================================
# This guide shows how to start each service in a separate terminal
# Run each command in a NEW terminal tab/window

echo "======================================"
echo "🚀 MICROSERVICES STARTUP GUIDE"
echo "======================================"
echo ""
echo "✅ Docker infrastructure is running:"
echo "   - Redis:               localhost:6379"
echo "   - User DB:            localhost:5432"
echo "   - Team DB:            localhost:5433"
echo "   - Project DB:         localhost:5434"
echo "   - Chat DB:            localhost:5435"
echo "   - Notification DB:    localhost:5436"
echo ""
echo "======================================"
echo "📋 START EACH SERVICE IN A NEW TERMINAL"
echo "======================================"
echo ""
echo "Open 7 NEW terminal tabs and run these commands:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 1: API Gateway (Port 4000)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/api-gateway && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 2: User Service (Port 3001)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/user-service && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 3: Team Service (Port 3002)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/team-service && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 4: Project Service (Port 3003)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/project-service && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 5: Chat Service (Port 3004)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/chat-service && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 6: Notification Service (Port 3005)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech/services/notification-service && npm run dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 7: Frontend (Port 3000)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd ~/webdev/latest_tech && npm run dev"
echo ""
echo "======================================"
echo "🔍 VERIFICATION"
echo "======================================"
echo ""
echo "After starting all services, verify they're running:"
echo ""
echo "  ./check-services.sh"
echo ""
echo "Or manually test each:"
echo "  curl http://localhost:4000/health  # API Gateway"
echo "  curl http://localhost:3001/health  # User Service"
echo "  curl http://localhost:3002/health  # Team Service"
echo "  curl http://localhost:3003/health  # Project Service"
echo "  curl http://localhost:3004/health  # Chat Service"
echo "  curl http://localhost:3005/health  # Notification Service"
echo ""
echo "======================================"
echo "🌐 ACCESS THE APP"
echo "======================================"
echo ""
echo "Frontend:          http://localhost:3000"
echo "API Gateway:       http://localhost:4000"
echo "Redis Commander:   http://localhost:8081"
echo ""
echo "======================================"
echo "⚠️  IMPORTANT NOTES"
echo "======================================"
echo ""
echo "1. Make sure you have .env files in each service directory"
echo "2. All services must have CLERK_SECRET_KEY set"
echo "3. API Gateway needs INTERNAL_JWT_SECRET and INTERNAL_API_KEY"
echo "4. Services need the same INTERNAL_JWT_SECRET as gateway"
echo ""
echo "To stop Docker infrastructure when done:"
echo "  docker compose down"
echo ""
